# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/osboxes/visualization.wavforhue

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/osboxes/visualization.wavforhue

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"visualization.wavforhue-0.0.2\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/osboxes/visualization.wavforhue/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/osboxes/visualization.wavforhue/CMakeFiles /home/osboxes/visualization.wavforhue/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/osboxes/visualization.wavforhue/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named addon-package

# Build rule for target.
addon-package: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 addon-package
.PHONY : addon-package

# fast build rule for target.
addon-package/fast:
	$(MAKE) -f CMakeFiles/addon-package.dir/build.make CMakeFiles/addon-package.dir/build
.PHONY : addon-package/fast

#=============================================================================
# Target rules for targets named visualization.wavforhue

# Build rule for target.
visualization.wavforhue: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 visualization.wavforhue
.PHONY : visualization.wavforhue

# fast build rule for target.
visualization.wavforhue/fast:
	$(MAKE) -f CMakeFiles/visualization.wavforhue.dir/build.make CMakeFiles/visualization.wavforhue.dir/build
.PHONY : visualization.wavforhue/fast

src/Main_gles.o: src/Main_gles.cpp.o
.PHONY : src/Main_gles.o

# target to build an object file
src/Main_gles.cpp.o:
	$(MAKE) -f CMakeFiles/visualization.wavforhue.dir/build.make CMakeFiles/visualization.wavforhue.dir/src/Main_gles.cpp.o
.PHONY : src/Main_gles.cpp.o

src/Main_gles.i: src/Main_gles.cpp.i
.PHONY : src/Main_gles.i

# target to preprocess a source file
src/Main_gles.cpp.i:
	$(MAKE) -f CMakeFiles/visualization.wavforhue.dir/build.make CMakeFiles/visualization.wavforhue.dir/src/Main_gles.cpp.i
.PHONY : src/Main_gles.cpp.i

src/Main_gles.s: src/Main_gles.cpp.s
.PHONY : src/Main_gles.s

# target to generate assembly for a file
src/Main_gles.cpp.s:
	$(MAKE) -f CMakeFiles/visualization.wavforhue.dir/build.make CMakeFiles/visualization.wavforhue.dir/src/Main_gles.cpp.s
.PHONY : src/Main_gles.cpp.s

src/VisGUIShader.o: src/VisGUIShader.cpp.o
.PHONY : src/VisGUIShader.o

# target to build an object file
src/VisGUIShader.cpp.o:
	$(MAKE) -f CMakeFiles/visualization.wavforhue.dir/build.make CMakeFiles/visualization.wavforhue.dir/src/VisGUIShader.cpp.o
.PHONY : src/VisGUIShader.cpp.o

src/VisGUIShader.i: src/VisGUIShader.cpp.i
.PHONY : src/VisGUIShader.i

# target to preprocess a source file
src/VisGUIShader.cpp.i:
	$(MAKE) -f CMakeFiles/visualization.wavforhue.dir/build.make CMakeFiles/visualization.wavforhue.dir/src/VisGUIShader.cpp.i
.PHONY : src/VisGUIShader.cpp.i

src/VisGUIShader.s: src/VisGUIShader.cpp.s
.PHONY : src/VisGUIShader.s

# target to generate assembly for a file
src/VisGUIShader.cpp.s:
	$(MAKE) -f CMakeFiles/visualization.wavforhue.dir/build.make CMakeFiles/visualization.wavforhue.dir/src/VisGUIShader.cpp.s
.PHONY : src/VisGUIShader.cpp.s

src/VisMatrixGLES.o: src/VisMatrixGLES.cpp.o
.PHONY : src/VisMatrixGLES.o

# target to build an object file
src/VisMatrixGLES.cpp.o:
	$(MAKE) -f CMakeFiles/visualization.wavforhue.dir/build.make CMakeFiles/visualization.wavforhue.dir/src/VisMatrixGLES.cpp.o
.PHONY : src/VisMatrixGLES.cpp.o

src/VisMatrixGLES.i: src/VisMatrixGLES.cpp.i
.PHONY : src/VisMatrixGLES.i

# target to preprocess a source file
src/VisMatrixGLES.cpp.i:
	$(MAKE) -f CMakeFiles/visualization.wavforhue.dir/build.make CMakeFiles/visualization.wavforhue.dir/src/VisMatrixGLES.cpp.i
.PHONY : src/VisMatrixGLES.cpp.i

src/VisMatrixGLES.s: src/VisMatrixGLES.cpp.s
.PHONY : src/VisMatrixGLES.s

# target to generate assembly for a file
src/VisMatrixGLES.cpp.s:
	$(MAKE) -f CMakeFiles/visualization.wavforhue.dir/build.make CMakeFiles/visualization.wavforhue.dir/src/VisMatrixGLES.cpp.s
.PHONY : src/VisMatrixGLES.cpp.s

src/VisShader.o: src/VisShader.cpp.o
.PHONY : src/VisShader.o

# target to build an object file
src/VisShader.cpp.o:
	$(MAKE) -f CMakeFiles/visualization.wavforhue.dir/build.make CMakeFiles/visualization.wavforhue.dir/src/VisShader.cpp.o
.PHONY : src/VisShader.cpp.o

src/VisShader.i: src/VisShader.cpp.i
.PHONY : src/VisShader.i

# target to preprocess a source file
src/VisShader.cpp.i:
	$(MAKE) -f CMakeFiles/visualization.wavforhue.dir/build.make CMakeFiles/visualization.wavforhue.dir/src/VisShader.cpp.i
.PHONY : src/VisShader.cpp.i

src/VisShader.s: src/VisShader.cpp.s
.PHONY : src/VisShader.s

# target to generate assembly for a file
src/VisShader.cpp.s:
	$(MAKE) -f CMakeFiles/visualization.wavforhue.dir/build.make CMakeFiles/visualization.wavforhue.dir/src/VisShader.cpp.s
.PHONY : src/VisShader.cpp.s

src/fft.o: src/fft.cpp.o
.PHONY : src/fft.o

# target to build an object file
src/fft.cpp.o:
	$(MAKE) -f CMakeFiles/visualization.wavforhue.dir/build.make CMakeFiles/visualization.wavforhue.dir/src/fft.cpp.o
.PHONY : src/fft.cpp.o

src/fft.i: src/fft.cpp.i
.PHONY : src/fft.i

# target to preprocess a source file
src/fft.cpp.i:
	$(MAKE) -f CMakeFiles/visualization.wavforhue.dir/build.make CMakeFiles/visualization.wavforhue.dir/src/fft.cpp.i
.PHONY : src/fft.cpp.i

src/fft.s: src/fft.cpp.s
.PHONY : src/fft.s

# target to generate assembly for a file
src/fft.cpp.s:
	$(MAKE) -f CMakeFiles/visualization.wavforhue.dir/build.make CMakeFiles/visualization.wavforhue.dir/src/fft.cpp.s
.PHONY : src/fft.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... addon-package"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... visualization.wavforhue"
	@echo "... src/Main_gles.o"
	@echo "... src/Main_gles.i"
	@echo "... src/Main_gles.s"
	@echo "... src/VisGUIShader.o"
	@echo "... src/VisGUIShader.i"
	@echo "... src/VisGUIShader.s"
	@echo "... src/VisMatrixGLES.o"
	@echo "... src/VisMatrixGLES.i"
	@echo "... src/VisMatrixGLES.s"
	@echo "... src/VisShader.o"
	@echo "... src/VisShader.i"
	@echo "... src/VisShader.s"
	@echo "... src/fft.o"
	@echo "... src/fft.i"
	@echo "... src/fft.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

